### ISSUE TITLE
Feature request: API Specification

### ISSUE THREAD

**Issue by Magicking** [ConsenSys/sobol-client#12]
Hi,

Is there an OpenAPI specification or something like that and/or are you interested in one ?

Having only a JS client API without specification prevents other languages to interconnect easily.

Regards,

**Comment by vleipnik-consensys** [comment]
Hi there - thank you for the question/feedback. We are definitely open to someone volunteering to write one :D It's not currently planned in the immediate future, but definitely something we will consider if there is enough demand. Are you currently wanting to integrate with a different language?

**Comment by Magicking** [comment]
Yes, either Python or Go for quick access and crawling purposes, having a specification would also imply that the services behind are tied to the specification, I'm not sure you want to have a volunteer do it ;)

**Comment by vleipnik** [comment]
This is done now, we have OpenAPI support. (Right click on your profile pic in Sobol, go to Applications, and you will find details there.)
